// Single source of truth for every file the dev server serves and the static build emits.
const html = 'text/html; charset=utf-8';
const css = 'text/css; charset=utf-8';
const js = 'text/javascript; charset=utf-8';
const text = 'text/plain; charset=utf-8';
const file = (relative, type) => ({ path: new URL(relative, import.meta.url), type });

export function createRoutes({ justBashBundle }) {
  return new Map([
    ['/', file('./seed.html', html)],
    ['/index.html', file('./seed.html', html)],
    ['/experiments.html', file('./index.html', html)],
    ['/index.css', file('./index.css', css)],
    ['/index.js', file('./index.js', js)],
    ['/vendor/lucide.js', file('../node_modules/lucide/dist/umd/lucide.min.js', js)],
    ['/vendor/just-bash.js', { body: justBashBundle, type: js }],
    ['/workshop.html', file('./workshop.html', html)],
    ['/workshop.css', file('./workshop.css', css)],
    ['/workshop.js', file('./workshop.js', js)],
    ['/workshop-runtime.js', file('./workshop-runtime.js', js)],
    ['/auth.js', file('./auth.js', js)],
    ['/seed.html', file('./seed.html', html)],
    ['/seed.css', file('./seed.css', css)],
    ['/seed.js', file('./seed.js', js)],
    ['/seed-runtime.js', file('./seed-runtime.js', js)],
    ['/shell.html', file('./shell.html', html)],
    ['/shell-runtime-notes.html', file('./shell-runtime-notes.html', html)],
    ['/shell.css', file('./shell.css', css)],
    ['/shell.js', file('./shell.js', js)],
    ['/shell-presets.js', file('./shell-presets.js', js)],
    ['/samples/opus-v5-564B.txt', file('../research/compression/samples/opus-v5-564B.sh', text)],
    ['/shell-linux.js', file('./shell-linux.js', js)],
    ['/shell-lite.js', file('./shell-lite.js', js)],
    ['/shell-protocol.js', file('./shell-protocol.js', js)],
    ['/vendor/xterm.js', file('../node_modules/@xterm/xterm/lib/xterm.js', js)],
    ['/vendor/xterm-fit.js', file('../node_modules/@xterm/addon-fit/lib/addon-fit.js', js)],
    ['/vendor/xterm.css', file('../node_modules/@xterm/xterm/css/xterm.css', css)],
    ['/linux/jq-linux-i386', file('./linux/jq-linux-i386', 'application/octet-stream')],
    ['/linux/curl-bridge.py', file('./linux/curl-bridge.py', text)],
    ['/linux/jq-COPYING', file('./linux/jq-COPYING', text)],
    ['/repl.html', file('./repl.html', html)],
    ['/repl-versions.html', file('./repl-versions.html', html)],
    ['/repl-console.html', file('./repl-console.html', html)],
    ['/repl-canvas.html', file('./repl-canvas.html', html)],
    ['/repl-notebook.html', file('./repl-notebook.html', html)],
    ['/repl-variants.css', file('./repl-variants.css', css)],
    ['/repl.css', file('./repl.css', css)],
    ['/repl.js', file('./repl.js', js)],
    ['/repl-engine.js', file('./repl-engine.js', js)],
    ['/repl-runtime.js', file('./repl-runtime.js', js)],
    ['/repl-sandbox.js', file('./repl-sandbox.js', js)],
    ['/samples/champion-386B.txt', file('../research/compression/samples/champion-386B.sh', text)],
    ['/domprout.html', file('./domprout.html', html)],
    ['/domprout.css', file('./domprout.css', css)],
    ['/domprout.js', file('./domprout.js', js)],
    ['/dom-agent.js', file('./dom-agent.js', js)],
    ['/dom-engine.js', file('./dom-engine.js', js)],
    ['/dom-sandbox.js', file('./dom-sandbox.js', js)],
    ['/shprout.txt', file('../shprout', text)],
    ['/approaches/classic.txt', file('../approaches/classic', text)],
    ['/approaches/syscap.txt', file('../approaches/syscap', text)],
    ['/approaches/self-mod.txt', file('../approaches/self-mod', text)],
  ]);
}
